server:
  port: 5050

eureka:
    client:
      serviceUrl:
          defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true


spring:
  application:
    name: user

  datasource:
    url: jdbc:postgresql://localhost:5222/user_microservice
    username: user_microservice
    password: user_microservice
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.BitronixJtaPlatform
        format_sql: true
    open-in-view: false


management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
  health:
    circuitbreakers:
      enabled: true
resilience4j:
  circuitbreaker:
    instances:
      Friend_Service:
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
