server:
  port: 6666

spring:
  application:
    name: Notification

  datasource:
    url: jdbc:postgresql://localhost:5227/notification_microservice
    username: notification_microservice
    password: notification_microservice
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

debug: true