server:
  port: 8888

spring:
  application:
    name: Publication

  datasource:
    url: jdbc:postgresql://localhost:5223/publication_microservice
    username: publication_microservice
    password: publication_microservice
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
    repositories:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

springdoc:
  api-docs:
    path: /api-docs
    enabled: true

debug: true